messenger4j:
  appSecret: 6a17b6f4d5f2d1f98d9ac4ea3decb31c
  verifyToken: AB
  pageAccessToken: EAAaISLtfMnUBAJeBe7TBv6rpKSjOZB73IApEOkLSZADyHpV5Ad9iKRHFmwwKbU0ooR1iZCqtdy2YATntnZCQDTZA3gEcYo53wyadgw0BvtE880JtUEgJvjlCHfJpaTzOf0voMRlaB2CsA0efcpxcY4oSpzZAAsmQgmKZAgxAs1jZBgZDZD
logging:
  level:
    com:
      github:
        messenger4j: INFO

